# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{nafizh}.github.io/nbdev_test/"

git_url = "https://github.com/{nafizh}/nbdev_test/tree/{branch}/"

def custom_doc_links(name): return None
